FROM python:3.9-slim

WORKDIR /app

COPY client.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


HEALTHCHECK --interval=30s --timeout=10s CMD nc -z localhost 12345


CMD ["python", "client.py"]
